services:
  spring-application:
    container_name: turnpage-dev
    image: ${DOCKER_USER_NAME}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    ports:
      - ${SPRING_OUTER_PORT}:${SPRING_INNER_PORT}
    volumes:
      - ./turnpage/logs:/app/logs

  nginx:
    container_name: nginx-dev
    image: nginx:latest
    volumes:
      - ./turnpage/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 80:80
    # 이 명령은 Nginx 서버를 계속 실행하고, 설정을 주기적으로 다시 로드하여 최신 상태를 유지, 포그라운드 실행
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  redis:
    container_name: redis-dev
    image: redis
    ports:
      - 6379:6379
