spring:
  datasource:
    url: jdbc:mysql://localhost:3306/turnpage?serverTimezone=Asia/Seoul
    username: bfly
    password: 20203085
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never
#      schema-locations: classpath:/schema.sql
#        data-locations: classpath:/data.sql

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


logging:
  level:
    org:
      hibernate:
        SQL: debug

  pattern:
  dateformat: yyyy-MM-dd HH:mm:ss.SSS, Asia/Seoul


cloud:
  aws:
    s3:
      bucket:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


public-data:
  book-search:
    encoding-service-key:
    decoding-service-key:
    url:

  bestseller:
    encoding-service-key:
    decoding-service-key:
    url: